"use client";

import { Bookmark, CalendarDays, Clock3, Edit3, Grid2X2, Play, Plus, Settings } from "lucide-react";
import { useState } from "react";
import { profile, profilePosts, profileSessions, savedPosts } from "@/data/match-data";

type Tab = "posts" | "sessions" | "saved";

export function ProfileView() {
  const [tab, setTab] = useState<Tab>("posts");
  return <main className="min-h-screen bg-[#f8f8fc] pb-28 text-slate-900"><div className="mx-auto max-w-md"><header className="flex items-center justify-between px-5 pb-4 pt-7"><h1 className="text-2xl font-bold">Perfil</h1><button aria-label="Configuración" className="rounded-xl p-2 text-slate-600 hover:bg-slate-100"><Settings size={21} /></button></header><section className="bg-white px-5 pb-6 pt-2"><div className="flex items-start gap-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-[1.6rem] bg-gradient-to-br from-violet-400 to-fuchsia-600 text-xl font-bold text-white shadow-lg shadow-violet-200">{profile.initials}</div><div className="min-w-0 flex-1"><div className="flex gap-2"><h2 className="truncate text-xl font-bold">{profile.name}</h2><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-emerald-500" /></div><p className="mt-0.5 text-sm text-slate-500">{profile.role}</p><p className="text-sm text-slate-500">{profile.career}</p></div></div><p className="mt-5 text-[15px] leading-6 text-slate-600">{profile.bio}</p><div className="mt-4 flex flex-wrap gap-2">{profile.subjects.map((subject) => <span key={subject} className="rounded-lg bg-violet-50 px-3 py-1.5 text-sm font-semibold text-violet-700">{subject}</span>)}</div><div className="mt-5 flex gap-3"><button className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-violet-600 py-3 text-sm font-bold text-white"><Edit3 size={16} /> Editar perfil</button><button className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 py-3 text-sm font-bold text-slate-700"><CalendarDays size={16} /> {profile.availability}</button></div></section><div className="mt-3 bg-white px-5"><div className="grid grid-cols-3"><TabButton active={tab === "posts"} onClick={() => setTab("posts")} icon={<Grid2X2 size={18} />} label="Publicaciones" /><TabButton active={tab === "sessions"} onClick={() => setTab("sessions")} icon={<CalendarDays size={18} />} label="Sesiones" /><TabButton active={tab === "saved"} onClick={() => setTab("saved")} icon={<Bookmark size={18} />} label="Guardados" /></div></div><section className="px-5 py-5">{tab === "posts" && <Posts />} {tab === "sessions" && <Sessions />} {tab === "saved" && <Saved />}</section></div></main>;
}

function TabButton({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) { return <button onClick={onClick} className={`flex flex-col items-center gap-1 border-b-2 py-3 text-xs font-bold ${active ? "border-violet-600 text-violet-700" : "border-transparent text-slate-400"}`}>{icon}{label}</button>; }
function Posts() { return <div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">Tus recursos</h2><p className="text-sm text-slate-500">3 publicaciones compartidas</p></div><button aria-label="Crear publicación" className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-600 text-white"><Plus size={21} /></button></div><div className="grid grid-cols-2 gap-3">{profilePosts.map((post) => <article key={post.id} className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className={`relative flex aspect-[4/3] items-end bg-gradient-to-br ${post.accent} p-3`}><span className="rounded-md bg-black/30 px-2 py-1 text-xs font-bold text-white">{post.type === "Video" && <Play className="mr-1 inline" size={12} fill="currentColor" />}{post.type}</span></div><div className="p-3"><p className="text-xs font-semibold text-violet-600">{post.subject}</p><h3 className="mt-1 text-sm font-bold leading-5">{post.title}</h3><p className="mt-2 text-xs text-slate-400">{post.views} vistas</p></div></article>)}</div></div>; }
function Sessions() { return <div><h2 className="text-lg font-bold">Tus sesiones</h2><p className="mb-4 text-sm text-slate-500">Organiza tu semana de estudio.</p><div className="space-y-3">{profileSessions.map((session) => <article key={session.id} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-violet-400 to-fuchsia-600 text-sm font-bold text-white">{session.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="font-bold">{session.person}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${session.accent}`}>{session.status}</span></div><p className="mt-0.5 text-sm font-medium text-violet-700">{session.subject}</p><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500"><span className="flex items-center gap-1"><CalendarDays size={13} />{session.time}</span><span className="flex items-center gap-1"><Clock3 size={13} />{session.duration}</span><span>{session.modality}</span></div></div></div></article>)}</div></div>; }
function Saved() { return <div><h2 className="text-lg font-bold">Guardados para después</h2><p className="mb-4 text-sm text-slate-500">Recursos que quieres revisar.</p><div className="space-y-3">{savedPosts.map((post) => <article key={post.id} className="flex overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className={`w-24 shrink-0 bg-gradient-to-br ${post.accent}`} /><div className="min-w-0 p-4"><p className="text-xs font-semibold text-violet-600">{post.subject} · {post.author}</p><h3 className="mt-1 font-bold leading-5">{post.title}</h3><button className="mt-3 text-sm font-bold text-violet-700">Ver recurso</button></div></article>)}</div></div>; }
